import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../app/globals.css'
import { Providers } from './providers'
import AuthGuard from '@/components/AuthGuard'
<<<<<<< HEAD
import { FooterGenerico } from '@/components/FooterGenerico'
=======
import FooterSelector from '@/components/FooterSelector'
>>>>>>> 348cb5b994368f3caeb83b6031aeb5e0dcac5dbf

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es' className='no-scrollbar'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AuthGuard>
            {children}
            <FooterSelector />
          </AuthGuard>
        </Providers>
      </body>
    </html>
  )
}
