import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../app/globals.css'
import { Providers } from './providers'
import AuthGuard from '@/components/AuthGuard'
import FooterSelector from '@/components/FooterSelector'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es' className='no-scrollbar'>
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <AuthGuard>
            <main>

            {children}
            </main>
            <FooterSelector />
          </AuthGuard>
        </Providers>
      </body>
    </html>
  )
}
