version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flowcare_db
    environment:
      POSTGRES_DB: flowcare_dev
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data: