import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex min-h-screen flex-col items-center justify-center ">
            <div className="flex items-center justify-between border-1 border-gray-300 shadow-lg rounded-lg min-h-[600px] min-w-[800px] p-8">
                
            <div>
                {children}
            </div>
            <div className="flex items-center justify-center">
                <Image src="/imagen_login.png" alt="imagen_login" width={500} height={500}/>
            </div>
            </div>
        </main>
      </body>
    </html>
  );
}
